### ISSUE TITLE
get lichess image to work with latest lichess commits

### ISSUE THREAD

**Issue by zenmatic** [zenmatic/lichess-docker#2]

**Comment by zenmatic** [comment]
```! @7ee6p0pm9 - Internal server error, for (GET) [/] ->

play.sbt.PlayExceptions$CompilationException: Compilation error[Symbol 'type lila.PackageObject' is missing from the classpath.
This symbol is required by 'package lila.common.package'.
Make sure that type PackageObject is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'package.class' was compiled against an incompatible version of lila.]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:34)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:34)
	at scala.Option.map(Option.scala:230)
	at play.sbt.run.PlayReload$.$anonfun$taskFailureHandler$1(PlayReload.scala:40)
	at scala.Option.map(Option.scala:230)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:35)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:28)
	at play.sbt.run.PlayReload$.$anonfun$compile$3(PlayReload.scala:63)
	at scala.util.Either$LeftProjection.map(Either.scala:573)
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:63)```
